### ISSUE TITLE
JS-Android  编译出错

### ISSUE THREAD

**Issue by tinybearc** [sdkbox/sdkbox-appodeal-sample#17]
### appodeal  版本：1.5.1.2

编译出错 cocos compile -p android

出错信息：
~~~
      [dx] Merged dex A (107 defs/126.8KiB) with dex B (1 defs/0.4KiB). Result is 108 defs/149.7KiB. Took 0.2s
       [dx] Merged dex A (108 defs/149.7KiB) with dex B (943 defs/967.8KiB). Result is 1051 defs/1378.6KiB. Took 0.4s
       [dx] Result compacted from 6763.8KiB to 5262.7KiB to save 1501.1KiB
       [dx] Merged dex A (1051 defs/1378.6KiB) with dex B (4882 defs/4201.9KiB). Result is 5933 defs/5262.7KiB. Took 1.3s
       [dx] Result compacted from 7982.2KiB to 6750.3KiB to save 1231.9KiB
       [dx] Merged dex A (5933 defs/5262.7KiB) with dex B (1335 defs/1530.8KiB). Result is 7268 defs/6750.3KiB. Took 0.8s
       [dx]
       [dx] UNEXPECTED TOP-LEVEL EXCEPTION:
       [dx] com.android.dex.DexException: Multiple dex files define Lcom/amazon/device/ads/AAXCreative;
       [dx] 	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:594)
       [dx] 	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:552)
       [dx] 	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:533)
       [dx] 	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:170)
       [dx] 	at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
       [dx] 	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:439)
       [dx] 	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:287)
       [dx] 	at com.android.dx.command.dexer.Main.run(Main.java:230)
       [dx] 	at com.android.dx.command.dexer.Main.main(Main.java:199)
       [dx] 	at com.android.dx.command.Main.main(Main.java:103)
       [dx]

BUILD FAILED
/Users/gbox/Android/sdk/tools/ant/build.xml:888: The following error occurred while executing this line:
/Users/gbox/Android/sdk/tools/ant/build.xml:890: The following error occurred while executing this line:
/Users/gbox/Android/sdk/tools/ant/build.xml:902: The following error occurred while executing this line:
/Users/gbox/Android/sdk/tools/ant/build.xml:283: null returned: 2

Total time: 1 minute 8 seconds
执行命令出错，返回值：1。
~~~

**Comment by hugohuang1111** [comment]
fixed
